openapi: 3.0.0
info:
  title: Proteria Group - Shipment API
  description: The Proteria Group Shipment API
  version: 1.0.0
externalDocs:
  description: Shipment API documentation
  url: 'https://proteria.atlassian.net/wiki/spaces/EXTPARTNERS/pages/2613641223/Proteria+Group+Shipment+API'
servers: 
    - url: 'https:///{basepath}/{version}/shipment'
      description: The shipment API URL
      variables:
        basepath:
          default: api.proteria.com
          enum:
            - api.proteria.com
            - sandbox.proteria.com
            - localhost
        version:
          default: v1
paths:
  /carriers:
    get:
      summary: get all possible carriers and their products
      operationId: getCarriers
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carriers'
  /shipment/booking:
    post:
      summary: create a shipment booking request
      description: |
        Creates a shipment booking request. 

        The correlationId of the request must be unique and is provided by the calling system.
        This id must be reused to fetch the result afterwards in /shipment/findByCorrelationId
      operationId: createBookingRequest
      requestBody:
        $ref: '#/components/requestBodies/ShipmentBookingRequest'
      responses:
        '202':
          description: item accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestConfirmation'
        '400':
          description: item rejected, see alerts for details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestConfirmation'

  /shipment/findByCorrelationId:
    get:
      summary: get shipment by correlationId
      description: | 
        With the correlationId from /shipment/booking, get the associated response
      operationId: findShipmentsByCorrelationId
      parameters:
        - name: correlationId
          in: query
          description: The correlationId from shipment/booking endpoint
          required: true
          schema:
            type: string
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShipmentResponse"
        400:
          description: "Invalid arguments"
        404:
          description: "Not found. Unknown correlationId"

  /resources/label/findByResourceId:
    get:
      summary: get label PDF by resourceId
      description: |
        Get label PDF by the given resourceId
      operationId: getLabelByResourceId
      parameters:
        - name: resourceId
          in: query
          description: resourceId of label that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Not found

  /resources/document/findByResourceId:
    get:
      summary: get document PDF by resourceId
      description: |
        Get document PDF by the given resourceId
      operationId: getDocumentByResourceId
      parameters:
        - name: resourceId
          in: query
          description: resourceId of document that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Not found

components:
  schemas:
    Carriers:
      type: array
      description: A list of carriers
      items:
        $ref: '#/components/schemas/Carrier'
    Carrier:
      required:
        - carrierId
        - carrierName
      description: Specification of a carrier
      type: object
      properties:
        carrierId:
          type: string
          example: postnord_no
        carrierName:
          type: string
          example: Postnord Norge
        carrierProducts:
          type: array
          description: list of this carrier products
          items:
            $ref: '#/components/schemas/CarrierProduct'
    CarrierProduct:
      required:
        - productId
      description: | 
        Specification of a carrier product. 
        Currently the rules and specifications of each product is not returned...
      type: object
      properties:
        productId:
          type: string
          example: MYPACK_BOX
        productName:
          type: string
          example: Mypack Box
        productServices:
          type: array
          description: list of this products additional services
          items:
            $ref: '#/components/schemas/ProductService'
    ProductService:
      description: Specification of a product additional service
      type: object
      properties:
        serviceId:
          type: string
          example: postnord_notification_email
        serviceName:
          type: string
          example: Postnord Notification Email
        serviceValue:
          type: string
          example: notifyme@somewhere.com
    ShipmentBookingRequest:
      required:
        - correlationId
        - carrier
        - carrierAccountNumber
        - carrierProduct
        - consignor
        - consignee
      type: object
      properties:
        correlationId:
          type: string
          example: YOUR-UNIQUE-BOOKING-REQUEST-ID-112233445566778899
          description: Your given unique id for this shipment, matches the correlationId in the response
        carrier:
          type: string
          example: postnord_no
          description: Given identifier of the carrier. Get all possible identifiers from carriers/
        carrierAccountNumber:
          type: string
          example: 12341234
          description: The carrier account number to book the shipment with.
        carrierProduct:
          type: string
          example: MYPACK_BOX
          description: Given identifier of the carrier product. Get all possible identifiers from carriers/
        services:
          type: array
          items:
            $ref: '#/components/schemas/ServiceItem'
        consignor:
          $ref: '#/components/schemas/AddressParty'
        consignee:
          $ref: '#/components/schemas/AddressParty'
        carrierMessage:
          type: string
          example: Entrance B, gate 44, blue doorbell
          description: Extra message to the carrier
        consigneeMessage:
          type: string
          example: Order XXXXX
          description: Extra message to the consignee
        consignorReference:
          type: string
          example: Ordernumber 1234
          description: Senders reference
        consigneeReference:
          type: string
          example: Purchase order 4321
          description: Receivers reference
        parcels:
          type: array
          items:
            $ref: '#/components/schemas/ParcelItem'
        customsInformation:
          $ref: '#/components/schemas/CustomsInformation'

    ServiceItem:
      required:
      - serviceId
      type: object
      properties:
        serviceId:
          type: string
          description: Given identifier of the carrier service. Get all possible identifiers from carriers/
        serviceValue:
          type: string
          description: Given value of the carrier service. Get all possible values from carriers/
    AddressParty:
      required:
        - name
        - address1
        - country
        - postCity
        - postCode
      type: object
      properties:
        name:
          type: string
          example: Ola Nordmann
        address1:
          type: string
          example: Andeveien 13
        address2:
          type: string
          example: 3. Etg.
        postCode:
          type: string
          example: '3131'
        postCity:
          type: string
          example: Andeby
        state:
          type: string
          example: 'false'
        country:
          type: string
          example: 'false'
        phone:
          type: string
          example: '+4799887766'
        email:
          type: string
          example: receiver@somewhere.com
        contactPersonName:
          type: string
          example: Name of contact person
        contactPersonPhone:
          type: string
          example: Phone of contact person
        contactPersonEmail:
          type: string
          example: Email of contact person
        taxInformations:
          type: array
          $ref: '#/components/schemas/TaxInformation'
            
    ParcelItem:
      description: |
        When creating a booking, provide the parcel information in this object.
        Provide you own unique identifier of the parcel as the correlationId
      required:
        - correlationId
        - parcelType
      type: object
      properties:
        correlationId:
          type: string
          description: Your given unique id for this parcel as provided in ShipmentBookingRequest.
        parcelType:
          type: string
          example: kolli (Trenger vi denne??)
        description:
          type: string
          example: Your description of the parcel (Trenger vi denne??)
        lengthCM:
          type: integer
          example: 10
        widthCM:
          type: integer
          example: 20
        heightCM:
          type: integer
          example: 30
        weightKG:
          type: integer
          example: 5
        volumeDM3:
          type: integer
          example: 1
        loadMeters:
          type: integer
          example: 2
        ParcelGoodsItems:
          type: array
          description: |
            List of goods items within this parcel.
          $ref: '#/components/schemas/ParcelGoodsItem'
    ParcelGoodsItem:
      properties:
        correlationId:
          type: string
        somethingElse:
          type: string
          description: TBD - This items is not defined yet....
    TaxInformation:
      type: object
      description: Tax Information (tin), applicable when shipping abroad.
      properties:
        tinNumber:
          type: string
          description: |
            The tax information number corresponding to the given tinType
          example: 123455677
        tinType:
          type: string
          description: |
            Type of Tax information
            Use BUSINESS_UNION for IOSS, and the IOSS number in tinNumber
            Use BUSINESS_NATIONAL for regular MVA, and the MVA number in tinNumber
          enum:
            - BUSINESS_NATIONAL
            - BUSINESS_UNION
            - PERSONAL_NATIONAL     
    CustomsInformation:
      type: object
      description: Customs Information, applicable when shipping abroad.
      properties:
        somethingCustoms:
          type: string
          description: TBD - This items is not defined yet....
    ShipmentResponse:
      properties:
        correlationId:
          type: string
          description: Unique key for this shipment. This will match the correlationId from the initial ShipmentBookingRequest
        status:
          type: string
          description: The status of this shipment booking
        shipment:
          description: The given shipment response
          $ref: '#/components/schemas/Shipment'
        alerts:
          type: array
          description: A list of alerts
          items:
            $ref: '#/components/schemas/Alert'
    Shipment:
      type: object
      properties:
        correlationId:
          type: string
          description: Unique key for this shipment. This will match the correlationId from the initial ShipmentBookingRequest
        consignmentNumber:
          type: string
        trackingNumber:
          type: string
        parcels:
          type: array
          description: list of parcels
          items:
            $ref: '#/components/schemas/Parcel'
        resources:
          type: array
          description: list of resources related to this shipment, for example label or other shipping documents
          items:
            $ref: '#/components/schemas/Resource'
    Parcel:
      type: object
      properties:
        correlationId:
          type: string
          description: Unique id for this parcel, matches the given correlationId from ParcelItem in the request
        carrierParcelNumber:
          type: string
          description: Carrier id for this parcel
        carrierTrackingNumber:
          type: string
          description: Carrier trackingNumber for this parcel
    Resource:
      type: object
      properties:
        resourceId:
          type: string
          description: The id of the resource. Use with /resources/{type}/findByResourceId to fetch the actual resource
          example: '123456789'
        resourceType:
          type: string
          description: The type of resource, each type corresponds to a url part to be used to fetch this resource
          enum:
            - label
            - document
    RequestConfirmation:
      type: object
      properties:
        correlationId:
          type: string
          description: |
            If successfully received, your correlationId is returned. Use the correlationId to get your response with /shipment/findByCorrelationId 
          example: '123456789'
        alerts:
          type: array
          description: A list of alerts. 
          items:
            $ref: '#/components/schemas/Alert'
    Alert:
      type: object
      properties:
        alertCode:
          type: string
          description: |
            Unique identifier of alert
          example: UNKNOWN_CARRIER_PRODUCT
        alertType:
          type: string
          description: Type of alert. 
          enum:
            - ERROR
            - WARNING
            - NOTE
        alertText:
          type: string
          description: description of alert
          example: The product value is unknown
  requestBodies:
    ShipmentBookingRequest:
      description: ShipmentBookingRequest
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ShipmentBookingRequest'


